CREATE TABLE PERSONA (id INTEGER NOT NULL, APELLIDOS VARCHAR(100), EMAIL VARCHAR(100), IDENTIFICACION VARCHAR(100), NOMBRE VARCHAR(100), PRIMARY KEY (id))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
